GET http://localhost:3000/mail


###

POST http://localhost:3000/mail
Content-Type: application/json

{
    "name": "test",
    "email": "test@mail.com",
    "subject": "elo",
    "message": "test",
    "applicationID": "in env file"
}